### ISSUE TITLE
Python AIOUSB

### ISSUE THREAD

**Issue by lyesba** [accesio/AIOUSB#28]
hi 

I want to use the Python for use the board, i have installed the AIOUSB librairy , but i don't want use it with C or Java
but u have this error when i want the install warrper languge

thank you 
(PS : sorry for my anglish)

cd python && make -f GNUMakefile python_test
make[1]: Entering directory '/home/pi/stage/AIOUSB-v1.116.1/AIOUSB/lib/wrappers/python'
PYTHONPATH=${PWD}/build/lib.linux-armv7l-2.7 python -c 'import AIOUSB; AIOUSB.AIOUSB_Init(); AIOUSB.AIOUSB_ListDevices()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named AIOUSB
GNUMakefile:138: recipe for target 'python_test' failed
make[1]: *** [python_test] Error 1
make[1]: Leaving directory '/home/pi/stage/AIOUSB-v1.116.1/AIOUSB/lib/wrappers/python'
GNUMakefile:81: recipe for target 'inplace_python' failed
make: *** [inplace_python] Error 2

**Comment by accesio** [comment]
This is an error where the build can't find AIOUSB.so

 1. Don't install AIOUSB before you build these wrappers. Build everything in place before installing

 2.  First build the lib directory in place 
```bash
cd $AIO_LIB_DIR
make
```

Now cd to wrappers and build there
```bash
cd $AIO_LIB_DIR/wrappers
make -f GNUMakefile inplace_python
```

If this fails it is generally because you don't have the python-dev libraries in stalled that give you Python.h

**Comment by accesio** [comment]
Have you gotten past this bug ? If not let me know otherwise I will close this.
